// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/dashboard" | "/help" | "/login" | "/register" | "/session/[sessionId]" | "/team/[teamId]" | "/team/[teamId]/settings"
type AppRouteHandlerRoutes = "/api/ai/analyze" | "/api/ai/chat" | "/api/ai/chat/stream" | "/api/auth/github-login" | "/api/auth/github/callback" | "/api/auth/github/start" | "/api/auth/login" | "/api/auth/logout" | "/api/auth/register" | "/api/debug-sessions" | "/api/debug-sessions/[id]" | "/api/debug-sessions/[id]/chat" | "/api/github/create-pr" | "/api/github/import-repo" | "/api/github/search" | "/api/run/execute" | "/api/teams" | "/api/teams/[id]/members" | "/api/user/me"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/ai/analyze": {}
  "/api/ai/chat": {}
  "/api/ai/chat/stream": {}
  "/api/auth/github-login": {}
  "/api/auth/github/callback": {}
  "/api/auth/github/start": {}
  "/api/auth/login": {}
  "/api/auth/logout": {}
  "/api/auth/register": {}
  "/api/debug-sessions": {}
  "/api/debug-sessions/[id]": { "id": string; }
  "/api/debug-sessions/[id]/chat": { "id": string; }
  "/api/github/create-pr": {}
  "/api/github/import-repo": {}
  "/api/github/search": {}
  "/api/run/execute": {}
  "/api/teams": {}
  "/api/teams/[id]/members": { "id": string; }
  "/api/user/me": {}
  "/dashboard": {}
  "/help": {}
  "/login": {}
  "/register": {}
  "/session/[sessionId]": { "sessionId": string; }
  "/team/[teamId]": { "teamId": string; }
  "/team/[teamId]/settings": { "teamId": string; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
